# -*- mode: ruby -*-
# vi: set ft=ruby :

# VirtualBoxとUbuntuの設定
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "virtualbox" do |vb|
  	vb.gui = true
  	vb.memory = "4096"
    vb.cpus = 2
    vb.customize [
      "modifyvm", :id,
      "--vram", "128", #ビデオメモリ確保
      "--clipboard", "bidirectional", #クリップボードの共有
      "--draganddrop", "bidirectional", #ドラッグアンドドロップ可能
    ]
  end

config.vm.provision "shell", inline: <<-SHELL

#ゲスト OSの更新
sudo apt-get update -y

#デスクトップ環境のインストール
sudo yes Y | sudo apt-get install -y --no-install-recommends lubuntu-desktop
sudo sleep 20s

# GUIモードの設定
sudo systemctl set-default graphical.target
sudo sleep 20s

#サイドのゲストOS更新
sudo apt-get update -y

# 日本語環境の設定
sudo apt-get install -y fonts-ipafont fonts-ipaexfont
sudo apt-get install -y language-pack-ja-base language-pack-ja ibus-mozc
sudo apt-get install -y firefox-locale-ja language-pack-gnome-ja
sudo update-locale LANG=ja_JP.UTF-8 LANGUAGE=”ja_JP:ja” LC_ALL=ja_JP.UTF-8
sudo localectl set-keymap jp106
sudo fc-cache -fv
fc-match IPAGothic
    
# 時刻の設定
sudo timedatectl set-timezone Asia/Tokyo
sudo systemctl enable systemd-timesyncd.service

# その他必要なソフトの追加
sudo apt-get install -y firefox vim wget curl tree git gedit

# vim設定カスタマイズ
sudo echo " " >> /etc/vimrc
sudo echo "set number" >> /etc/vimrc
sudo echo "set title" >> /etc/vimrc
sudo echo "syntax on" >> /etc/vimrc
sudo echo "set smartindent" >> /etc/vimrc
sudo echo " " >> /etc/vimrc
sudo echo "highlight Comment ctermfg=Green" >> /etc/vimrc
sudo echo "highlight Constant ctermfg=Red" >> /etc/vimrc
sudo echo "highlight Identifier ctermfg=Cyan" >> /etc/vimrc
sudo echo "highlight Statement ctermfg=Yellow" >> /etc/vimrc
sudo echo "highlight Title ctermfg=Magenta" >> /etc/vimrc
sudo echo "highlight Special ctermfg=Magenta" >> /etc/vimrc
sudo echo "highlight PreProc ctermfg=Magenta" >> /etc/vimrc
sudo echo " " >> /etc/vimrc
sudo echo "set tabstop=2" >> /etc/vimrc
sudo echo "set shiftwidth=2" >> /etc/vimrc

# ゲストOSの再起動
sudo shutdown -r now
    
SHELL

end