# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"
  config.vm.network "private_network", ip: "192.168.33.1" #host only adapter
  config.vm.network "forwarded_port", guest: 8080, host: 8080   # HTTP
  config.vm.network "forwarded_port", guest: 9090, host: 9090  # HTTPS

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2046"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y update
    sudo yum -y upgrade
    sudo yum install -y tree git vim wget
    sudo yum install -y java-11-openjdk.x86_64 
    sudo yum install -y java-11-openjdk-headless.x86_64
    sudo wget https://github.com/WebGoat/WebGoat/releases/download/v8.0.0.M24/webgoat-server-8.0.0.M24.jar
    sudo wget https://github.com/WebGoat/WebGoat/releases/download/v8.0.0.M24/webwolf-8.0.0.M24.jar
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    sudo echo " " >> /etc/vimrc
    sudo echo "set number" >> /etc/vimrc
    sudo echo "set title" >> /etc/vimrc
    sudo echo "syntax on" >> /etc/vimrc
    sudo echo "set smartindent" >> /etc/vimrc
    sudo echo " " >> /etc/vimrc
    sudo echo "highlight Comment ctermfg=Green" >> /etc/vimrc
    sudo echo "highlight Constant ctermfg=Red" >> /etc/vimrc
    sudo echo "highlight Identifier ctermfg=Cyan" >> /etc/vimrc
    sudo echo "highlight Statement ctermfg=Yellow" >> /etc/vimrc
    sudo echo "highlight Title ctermfg=Magenta" >> /etc/vimrc
    sudo echo "highlight Special ctermfg=Magenta" >> /etc/vimrc
    sudo echo "highlight PreProc ctermfg=Magenta" >> /etc/vimrc
    sudo echo " " >> /etc/vimrc
    sudo echo "set tabstop=2" >> /etc/vimrc
    sudo echo "set shiftwidth=2" >> /etc/vimrc
  SHELL

  config.vm.provision "shell", run: "always", privileged: false, inline: <<-SHELL
    sudo java -jar webgoat-server-8.0.0.M24.jar --server.address=0.0.0.0 &
    sleep 2m
    sudo java -jar webwolf-8.0.0.M24.jar --server.address=0.0.0.0 &
  SHELL

end

