# -*- mode: ruby -*-
# vi: set ft=ruby :

# VirtualBoxとUbuntuの設定
Vagrant.configure(2) do |config|
  config.vm.box = "aiit-alpha-team/boxes/Lubuntu-20.04_EC-Cube-4.1.0"
  config.vm.provider "virtualbox" do |vb|
  	vb.gui = true
  	vb.memory = "4096"
    vb.cpus = 2
    vb.customize [
      "modifyvm", :id,
      "--vram", "128", #ビデオメモリ確保
      "--clipboard", "bidirectional", #クリップボードの共有
      "--draganddrop", "bidirectional", #ドラッグアンドドロップ可能
    ]
  end
end

# OSログインアカウント id:vagrant pass:vagrant
# EC-Cube管理者アカウント id:admin pass:adminpasswd
